# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['mtu_optimizer.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'mtu_optimizer',
        'mtu_optimizer.core',
        'mtu_optimizer.dns',
        'mtu_optimizer.tweaks',
        'mtu_optimizer.servers',
        'mtu_optimizer.system',
        'mtu_optimizer.scoring',
        'mtu_optimizer.profiles',
        'mtu_optimizer.backup',
        'mtu_optimizer.speedtest',
        'mtu_optimizer.monitor',
        'mtu_optimizer.export',
        'mtu_optimizer.ui',
        'mtu_optimizer.menu',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='mtu_optimizer',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
